11.11.2019 17:53:07:
System.IO.FileNotFoundException: Could not find file 'D:\Projects\C#\Tester\Tester\bin\Release\netcoreapp3.0\publish\appsettings.json'.
File name: 'D:\Projects\C#\Tester\Tester\bin\Release\netcoreapp3.0\publish\appsettings.json'
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.File.AsyncStreamReader(String path, Encoding encoding)
   at System.IO.File.InternalReadAllTextAsync(String path, Encoding encoding, CancellationToken cancellationToken)
   at Tester.Program.TryParseConfigAsync() in D:\Projects\C#\Tester\Tester\Program.cs:line 228
11.11.2019 17:54:08:
System.Net.Http.HttpRequestException: Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение.
 ---> System.Net.Sockets.SocketException (10061): Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Tester.Program.SendClientIncomingRequestAsync(String RequestNumber) in D:\Projects\C#\Tester\Tester\Program.cs:line 182
11.11.2019 17:54:22:
System.Net.Http.HttpRequestException: Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение.
 ---> System.Net.Sockets.SocketException (10061): Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Tester.Program.SendClientIncomingRequestAsync(String RequestNumber) in D:\Projects\C#\Tester\Tester\Program.cs:line 182
13.11.2019 19:47:23:
System.Net.Http.HttpRequestException: Сервис недоступен.
   at Tester.Program.WaitForRequestFinished(Int32 requestId, CallFinishedSuccess success) in D:\Projects\C#\Tester\Tester\Program.cs:line 118
13.11.2019 19:47:23:
System.Net.Http.HttpRequestException: Сервис недоступен.
   at Tester.Program.WaitForRequestFinished(Int32 requestId, CallFinishedSuccess success) in D:\Projects\C#\Tester\Tester\Program.cs:line 118
13.11.2019 19:47:23:
System.Net.Http.HttpRequestException: Сервис недоступен.
   at Tester.Program.WaitForRequestFinished(Int32 requestId, CallFinishedSuccess success) in D:\Projects\C#\Tester\Tester\Program.cs:line 118
13.11.2019 19:47:23:
System.Net.Http.HttpRequestException: Сервис недоступен.
   at Tester.Program.WaitForRequestFinished(Int32 requestId, CallFinishedSuccess success) in D:\Projects\C#\Tester\Tester\Program.cs:line 118
13.11.2019 19:47:23:
System.Net.Http.HttpRequestException: Сервис недоступен.
   at Tester.Program.WaitForRequestFinished(Int32 requestId, CallFinishedSuccess success) in D:\Projects\C#\Tester\Tester\Program.cs:line 118
13.11.2019 19:47:23:
System.Net.Http.HttpRequestException: Сервис недоступен.
   at Tester.Program.WaitForRequestFinished(Int32 requestId, CallFinishedSuccess success) in D:\Projects\C#\Tester\Tester\Program.cs:line 118
13.11.2019 19:47:23:
System.Net.Http.HttpRequestException: Сервис недоступен.
   at Tester.Program.WaitForRequestFinished(Int32 requestId, CallFinishedSuccess success) in D:\Projects\C#\Tester\Tester\Program.cs:line 118
13.11.2019 19:47:23:
System.Net.Http.HttpRequestException: Сервис недоступен.
   at Tester.Program.WaitForRequestFinished(Int32 requestId, CallFinishedSuccess success) in D:\Projects\C#\Tester\Tester\Program.cs:line 118
13.11.2019 19:47:24:
System.Net.Http.HttpRequestException: Сервис недоступен.
   at Tester.Program.WaitForRequestFinished(Int32 requestId, CallFinishedSuccess success) in D:\Projects\C#\Tester\Tester\Program.cs:line 118
13.11.2019 19:47:24:
System.Net.Http.HttpRequestException: Сервис недоступен.
   at Tester.Program.WaitForRequestFinished(Int32 requestId, CallFinishedSuccess success) in D:\Projects\C#\Tester\Tester\Program.cs:line 118
13.11.2019 19:47:24:
System.Net.Http.HttpRequestException: Сервис недоступен.
   at Tester.Program.WaitForRequestFinished(Int32 requestId, CallFinishedSuccess success) in D:\Projects\C#\Tester\Tester\Program.cs:line 118
13.11.2019 19:47:24:
System.Net.Http.HttpRequestException: Сервис недоступен.
   at Tester.Program.WaitForRequestFinished(Int32 requestId, CallFinishedSuccess success) in D:\Projects\C#\Tester\Tester\Program.cs:line 118
13.11.2019 19:47:24:
System.Net.Http.HttpRequestException: Сервис недоступен.
   at Tester.Program.WaitForRequestFinished(Int32 requestId, CallFinishedSuccess success) in D:\Projects\C#\Tester\Tester\Program.cs:line 118
13.11.2019 19:47:24:
System.Net.Http.HttpRequestException: Сервис недоступен.
   at Tester.Program.WaitForRequestFinished(Int32 requestId, CallFinishedSuccess success) in D:\Projects\C#\Tester\Tester\Program.cs:line 118
13.11.2019 19:47:24:
System.Net.Http.HttpRequestException: Сервис недоступен.
   at Tester.Program.WaitForRequestFinished(Int32 requestId, CallFinishedSuccess success) in D:\Projects\C#\Tester\Tester\Program.cs:line 118
13.11.2019 19:47:24:
System.Net.Http.HttpRequestException: Сервис недоступен.
   at Tester.Program.WaitForRequestFinished(Int32 requestId, CallFinishedSuccess success) in D:\Projects\C#\Tester\Tester\Program.cs:line 118
13.11.2019 19:47:42:
System.Net.Http.HttpRequestException: Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение.
 ---> System.Net.Sockets.SocketException (10061): Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Tester.Program.SendClientIncomingRequestAsync(String RequestNumber) in D:\Projects\C#\Tester\Tester\Program.cs:line 205
13.11.2019 19:47:56:
System.Net.Http.HttpRequestException: Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение.
 ---> System.Net.Sockets.SocketException (10061): Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Tester.Program.SendClientIncomingRequestAsync(String RequestNumber) in D:\Projects\C#\Tester\Tester\Program.cs:line 205
13.11.2019 19:48:10:
System.Net.Http.HttpRequestException: Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение.
 ---> System.Net.Sockets.SocketException (10061): Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Tester.Program.SendClientIncomingRequestAsync(String RequestNumber) in D:\Projects\C#\Tester\Tester\Program.cs:line 205
13.11.2019 19:49:17:
System.Net.Http.HttpRequestException: Сервис недоступен.
   at Tester.Program.WaitForRequestFinished(Int32 requestId, CallFinishedSuccess success) in D:\Projects\C#\Tester\Tester\Program.cs:line 118
13.11.2019 19:49:17:
System.Net.Http.HttpRequestException: Сервис недоступен.
   at Tester.Program.WaitForRequestFinished(Int32 requestId, CallFinishedSuccess success) in D:\Projects\C#\Tester\Tester\Program.cs:line 118
13.11.2019 19:49:18:
System.Net.Http.HttpRequestException: Сервис недоступен.
   at Tester.Program.WaitForRequestFinished(Int32 requestId, CallFinishedSuccess success) in D:\Projects\C#\Tester\Tester\Program.cs:line 118
13.11.2019 19:49:18:
System.Net.Http.HttpRequestException: Сервис недоступен.
   at Tester.Program.WaitForRequestFinished(Int32 requestId, CallFinishedSuccess success) in D:\Projects\C#\Tester\Tester\Program.cs:line 118
13.11.2019 19:49:20:
System.Net.Http.HttpRequestException: Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение.
 ---> System.Net.Sockets.SocketException (10061): Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Tester.Program.SendClientIncomingRequestAsync(String RequestNumber) in D:\Projects\C#\Tester\Tester\Program.cs:line 205
13.11.2019 19:49:52:
System.Net.Http.HttpRequestException: Сервис недоступен.
   at Tester.Program.WaitForRequestFinished(Int32 requestId, CallFinishedSuccess success) in D:\Projects\C#\Tester\Tester\Program.cs:line 118
13.11.2019 19:49:52:
System.Net.Http.HttpRequestException: Сервис недоступен.
   at Tester.Program.WaitForRequestFinished(Int32 requestId, CallFinishedSuccess success) in D:\Projects\C#\Tester\Tester\Program.cs:line 118
13.11.2019 19:49:53:
System.Net.Http.HttpRequestException: Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение.
 ---> System.Net.Sockets.SocketException (10061): Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Tester.Program.SendClientIncomingRequestAsync(String RequestNumber) in D:\Projects\C#\Tester\Tester\Program.cs:line 205
13.11.2019 19:50:07:
System.Net.Http.HttpRequestException: Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение.
 ---> System.Net.Sockets.SocketException (10061): Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Tester.Program.SendClientIncomingRequestAsync(String RequestNumber) in D:\Projects\C#\Tester\Tester\Program.cs:line 205
13.11.2019 19:50:18:
System.Net.Http.HttpRequestException: Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение.
 ---> System.Net.Sockets.SocketException (10061): Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Tester.Program.SendClientIncomingRequestAsync(String RequestNumber) in D:\Projects\C#\Tester\Tester\Program.cs:line 205
13.11.2019 19:50:47:
System.Net.Http.HttpRequestException: Сервис недоступен.
   at Tester.Program.WaitForRequestFinished(Int32 requestId, CallFinishedSuccess success) in D:\Projects\C#\Tester\Tester\Program.cs:line 118
13.11.2019 19:50:58:
System.Net.Http.HttpRequestException: Сервис недоступен.
   at Tester.Program.WaitForRequestFinished(Int32 requestId, CallFinishedSuccess success) in D:\Projects\C#\Tester\Tester\Program.cs:line 118
